import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { FaSignOutAlt } from "react-icons/fa";
import { api } from "~/utils/api";

const Posts = () => {
  const { data } = api.post.getSome.useQuery();

  return (
    <div>
      {data?.map((post) => (
        <div key={post.id}>{post.content}</div>
      ))}
    </div>
  );
};
export default function Home() {
  const { user, isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Posts />
      </main>

      {!isSignedIn ? (
        <footer className="fixed bottom-0 left-0 flex flex-col items-center space-y-3 rounded-tr bg-emerald-700 px-12 py-7">
          <span className="text-2xl font-bold">Join the Muttering.</span>
          <SignInButton mode="modal">
            <button className="w-fit rounded bg-gray-100 px-5 py-2 text-lg text-emerald-700 ">
              Sign In
            </button>
          </SignInButton>
        </footer>
      ) : (
        user && (
          <footer className="fixed bottom-12 left-12">
            <div className="flex items-center space-x-4 rounded-full p-4 hover:bg-gray-900">
              <Image
                src={user.imageUrl}
                alt="profile pic"
                width={42}
                height={42}
                className="rounded-full"
              />
              <div className="flex flex-col">
                <button className="w-full text-left">Mutter something,</button>
                <span className="text-left text-gray-400">
                  @{user.username}
                </span>
              </div>
              <SignOutButton>
                <button className="h-[42px] w-[42px] rounded-full bg-emerald-700 p-2">
                  <FaSignOutAlt className="h-full w-full" />
                </button>
              </SignOutButton>
            </div>
          </footer>
        )
      )}
    </>
  );
}
