import Head from "next/head";
import Login from "~/components/Login";
import MakePost from "~/components/MakePost";
import Post from "~/components/Post";
import { api } from "~/utils/api";

const Posts = () => {
  const { data } = api.post.getSome.useQuery();

  return (
    <div className="grid w-full space-y-[2px] border-x-2 border-gray-600 bg-gray-600">
      {data?.map((post) => (
        <Post key={post.id} id={post.id} />
      ))}
    </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative mx-auto flex min-h-screen flex-col items-center lg:max-w-2xl">
        <MakePost />
        <Posts />
      </main>

      <Login />
    </>
  );
}
