import { ChevronLeft } from "lucide-react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { Button } from "~/@/components/ui/button";
import Login from "~/components/Login";

const Post = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="relative mx-auto flex min-h-screen flex-col items-center border-x-[1px] border-gray-600 lg:max-w-2xl">
        <header>
          <Button variant="ghost" size="icon" asChild={true}>
            <Link href="/">
              <ChevronLeft />
            </Link>
          </Button>
        </header>
      </section>

      <Login />
    </>
  );
};

export default Post;
